import os

env = Environment()
num_cpu = int(os.environ.get('NUM_CPU', 4))
env.SetOption('num_jobs', num_cpu)

env.Append(CPPPATH = ['/vsim/framework/'])
env.Append(LIBPATH = ['/vsim/framework/lib'])

env.AppendUnique(LIBS = ['osg', 'osgGA', 'osgDB', 'osgUtil', 'osgViewer', 'osgShadow'])
env.AppendUnique(LIBS = ['pthread'])
env.AppendUnique(LIBS = ['tgfunits', 'tgfecp', 'tgfutil', 'tgfspp', 'tgfsdp'])
env.AppendUnique(LIBS = ['boost_system', 'boost_thread', 'boost_chrono', 'boost_signals', 'tgfairspace'])

viewer = env.Program('osgtest', 
	Glob('*.cpp'), 
	CCFLAGS='-O2 -g -std=c++0x -DHAVE_GMTL'
)

Default(viewer)
