Import('qenv')

UICS = Glob('*.ui')

for x in UICS:
	temp = qenv.Uic4(source = x, duplicate=0)
	Default(temp)
	
CPPS = Glob('*.cpp')

lib = qenv.SharedLibrary(target = '#/lib/pluginDateTimeControls',
 source = CPPS,
 CPPPATH=['.','#', '#/src/core', '#/src/gui', '#/.build/src/plugins/dateTimeControls', qenv['CPPPATH']])
Default(lib)

